POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3NjA5OTU4NzJ9.I8D3277qqwSASB6Fli13wp5bYK_2puTyDcZ53zi9pdc

{
    "author": "Gabriel O'Meara",
    "url": "https://blog.gamesight.io/the-metamorphosis-of-gta-v-on-twitch/",
    "title": "Part 2 - The Metamorphosis of GTA V Online",
    "likes": 12,
    "year": 2021
}