POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyQGdtYWlsLmNvbSIsImlkIjoyLCJpYXQiOjE3NjA4MDU2Njl9.mSVmLwdlMEQzgaa-qhTo8j73XVm0hxoJvSomi8uvLu8

{
    "author": "pekoeblaze",
    "url": "https://pekoeblaze.wordpress.com/2025/05/16/outlast-2013-how-to-make-a-good-linear-horror-game/",
    "title": "Outlast” (2013) – How To Make A GOOD Linear Horror Game",
    "likes": 10
}